name: DevOps Pipeline - Fase 2 (CI/CD)

on:
  push:
    branches: [ "main", "feature-fase2" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar o Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Executar testes automatizados
      run: npm test

  delivery-and-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature-fase2'
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar ambiente Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Executar Build Real da Imagem (Validação do Dockerfile)
      run: |
        docker build -t pedrokbock/api-devops-pucrs:latest .
        echo "Sucesso: Dockerfile compilado sem erros no pipeline!"

    - name: Executar Script de Deploy Automatizado (CD)
      run: |
        chmod +x ./scripts/deploy.sh
        ./scripts/deploy.sh
